# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmployeeManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmployeeManager
  pod 'SnapKit', '~> 5.6.0'
  pod 'FirebaseFirestore'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'EmployeeManagerTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  end

  target 'EmployeeManagerUITests' do
    # Pods for testing
  end

end
